module.exports = {
	AppFinancedProposalParams: 'AppFinancedProposalParams',
	AppFinancedUserExchangeParams: 'AppFinancedUserExchangeParams',
	AppFinancedUserExchangeConfirmParams: 'AppFinancedUserExchangeConfirmParams',
	CommentData: 'CommentData',
	AddAppParams: 'AddAppParams',
	AuthParamsCreateModel: 'AuthParamsCreateModel',
	ClientParamsCreateModel: 'ClientParamsCreateModel',
	ClientParamsCreatePublishDoc: 'ClientParamsCreatePublishDoc',
	ClientParamsCreateIdentifyDoc: 'ClientParamsCreateIdentifyDoc',
	ClientParamsCreateTryDoc: 'ClientParamsCreateTryDoc',
	ClientParamsCreateChooseDoc: 'ClientParamsCreateChooseDoc',
	ClientParamsCreateModelDoc: 'ClientParamsCreateModelDoc',
	ModelExpertAddMemberParams: 'ModelExpertAddMemberParams',
	ModelExpertDelMemberParams: 'ModelExpertDelMemberParams',
}